### ISSUE TITLE
Incorrect ProjectRoot used

### ISSUE THREAD

**Issue by mleutner** [ocassio/testcafe-reporter-custom#5]
The testcafe-reporter-custom implementation assumes the wrong ProjectRoot (index.js:6) when used together with the testcafe/testcafe docker image and its start script. The issue can be generalized and affects any usage with this pattern.

The issue is related to a abs path problem, the process.mainModule and the global installation of testcafe as provided by the testcafe docker image.

testcafe-docker.sh (docker image):
#!/bin/sh
[...]
node /usr/lib/node_modules/testcafe/bin/testcafe-with-v8-flag-filter.js --ports 1337,1338 "$@"

process.mainModule (similar to below):
Module {
  id: '.',
  exports: {},
  parent: null,
  filename: '/usr/lib/node_modules/testcafe/bin/testcafe-with-v8-flag-filter.js',
  loaded: false,
  children: [],
  paths:
   [ '/usr/lib/node_modules/',
     '/usr/node_modules/,
     '/node_modules' ] }

The following line incorrectly assigns "/usr/lib" to "projectRoot". The effect is that relative paths e.g. project/index.js or reporter.config.js are not valid within CWD.
const projectRoot = process.mainModule.paths[0].split('node_modules')[0].slice(0, -1);

Proposed patch will be may look like this:

--- index.js	2021-04-08 09:09:59.491599382 +0200
+++ index.js.upd	2021-04-08 09:07:08.535429998 +0200
@@ -3,7 +3,13 @@
 const { loadConfig } = require('./utils/config.utils');
 const { registerTsNode } = require('./utils/typescript.utils');
 
-const projectRoot = process.mainModule.paths[0].split('node_modules')[0].slice(0, -1);
+var projectRoot = "";
+
+if (!fs.existsSync(process.cwd() + path.sep + 'node_modules')) {
+    projectRoot = process.cwd() + path.sep;
+} else {
+    projectRoot = process.mainModule.paths[0].split('node_modules')[0].slice(0, -1);
+}
 
 const configPath = path.resolve(projectRoot, 'reporter.config.js');
 const config = loadConfig(configPath);

By selecting the process.cwd and test for "node_modules" we check for a project in the current working directory, otherwise we fallback to the previous imlementation...

**Comment by ocassio** [comment]
Hi @mleutner!
Thanks for your help. The fix has been included in version 1.1.1.
