### ISSUE TITLE
Error when using ES modules

### ISSUE THREAD

**Issue by TrevorKarjanis** [ocassio/testcafe-reporter-custom#9]
An error occurs when trying to create a custom reporter that is an ES module instead of CommonJS. There many modules, like [node-fetch](https://github.com/node-fetch/node-fetch/blob/HEAD/docs/v3-UPGRADE-GUIDE.md), that now only support ES modules. Would it be possible to use them here?

```bash
ERROR Error [ERR_REQUIRE_ESM]: require() of ES Module /testcafe-reporter-custom-issue-9/reporter/index.js from /testcafe-reporter-custom-issue-9/node_modules/testcafe-reporter-custom/lib/index.js not supported.
Instead change the require of /testcafe-reporter-custom-issue-9/reporter/index.js in /testcafe-reporter-custom-issue-9/node_modules/testcafe-reporter-custom/lib/index.js to a dynamic import() which is available in all CommonJS modules.
```

Steps to Reproduce
[Reproduction on GitHub](https://github.com/TrevorKarjanis/testcafe-reporter-custom-issue-9)
1. Run `npm init`.
2. Set the type to "module" in `package.json`.
2. Run `npm install testcafe testcafe-reporter-custom`.
3. Create a [custom reporter module](https://github.com/TrevorKarjanis/testcafe-reporter-custom-issue/blob/main/reporter/index.js) in `reporter/index.js`.
4. Run `node testcafe chrome tests --reporter custom`.

Environment
- testcafe@1.18.1
- testcafe-reporter-custom@1.1.1

**Comment by TrevorKarjanis** [comment]
Unfortunately, switching to a dynamic import, which may have been a backwards compatible solution, produces an error.
```bash
ERROR An uncaught error occurred in the "custom" reporter's "reportTaskStart" method. Error details:
Error: Not implemented
    at ReporterPluginHost.reportTaskStart (node_modules/testcafe/src/reporter/plugin-host.js:157:15)
    at Reporter.dispatchToPlugin (node_modules/testcafe/src/reporter/index.js:199:38)
    at Reporter._onceTaskStartHandler (node_modules/testcafe/src/reporter/index.js:221:20)
    at node_modules/testcafe/src/reporter/index.js:342:51
    at node_modules/testcafe/src/utils/async-event-emitter.ts:19:20
    at node_modules/emittery/index.js:69:13
    at Array.map (<anonymous>)
    at Task.emit (node_modules/emittery/index.js:67:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```javascript
// node_modules/testcafe-reporter-custom/lib/index.js
module.exports = function() {
    let logic = await import(reporterPath);

    if (logic.default) {
        logic = logic.default;
    }

    if (logic instanceof Function) {
        logic = logic();
    }

    return logic;
}
```

**Comment by TrevorKarjanis** [comment]
ESLint addressed this issue by [adding support for the `.csj` extension](https://github.com/eslint/rfcs/blob/main/designs/2019-esm-compatibilty/README.md). This way CommonJS modules can exist in a ESM workspace without converting the project. The equivalent here might be to support a priority of `reporter.config.js`, `reporter.config.cjs`, `reporter/index.js`, and `reporter/index.csj`.

**Comment by ocassio** [comment]
Hi @TrevorKarjanis, thanks for the analysis.
I've managed to make it work for the basic cases, but still struggling with ts-node support and didn't check some edge cases.
Unfortunately, I don't have much of a free time right now, but I'll try to figure it out as soon as I'll have some.

**Comment by ocassio** [comment]
Hi @TrevorKarjanis.
Unfortunately I couldn't find a completely universal solution which will work with ts-node, so I've added an optional property in the configuration file called `moduleType` which can be used in order to specify whether your reporter uses CommonJS or ES Modules. Configuration example can be found [here](https://github.com/ocassio/testcafe-reporter-custom/tree/master/examples/es-modules).
You can try it out with version 1.2.0.

**Comment by TrevorKarjanis** [comment]
That'll do. Your effort is appreciated. I'll give it a try!
